apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: okx371w00-nodejs
  janus-idp.io/tekton: okx371w00-nodejs
  backstage.io/kubernetes-id: okx371w00-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: okx371w00-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
